### ISSUE TITLE
Issue using docker compose urls

### ISSUE THREAD

**Issue by lucas-aragno** [apollographql/apollo-link#375]
**Intended outcome:**

I had my app running using `link: createHttpLink({ uri: process.env.GRAPHQL_ENDPOINT, fetch }),` 

here my endpoint is `GRAPHQL_ENDPOINT = 'http://web-api:5000/graphql'`

since my docker-compose file looks like this:

```yaml
  web-api:
    container_name: 'web-api'
    build: './services/web-api'
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
  web-app:
    container_name: 'web-app'
....
```

I always this format for urls on docker-compose: 
https://docs.docker.com/docker-cloud/apps/service-links/#service-link-environment-variables

The actual outcome that I got was 

```
react-apollo.browser.umd.js?df32:545 Unhandled (in react-apollo:Apollo(AuthHandler)) Error: Network error: Failed to fetch
    at new ApolloError (webpack-internal:///48:36:28)
    at ObservableQuery.currentResult (webpack-internal:///44:94:24)
    at GraphQL.dataForChild (webpack-internal:///74:540:62)
    at GraphQL.render (webpack-internal:///74:590:33)
    at callMethod (webpack-internal:///160:511:12)
    at GraphQL.eval [as render] (webpack-internal:///160:522:12)
    at renderComponent (webpack-internal:///9:694:24)
    at GraphQL.forceUpdate (webpack-internal:///9:927:3)
    at GraphQL.forceRenderChildren (webpack-internal:///74:508:26)
    at next (webpack-internal:///74:483:27)
```

I tried to change it to use `localhost:5000` instead but docker doesn't like that so right now im working w/o docker (with `localhost`) and works just fine, but I was wondering if you tried to use this with docker-compose
